# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93163d6ee7dbe75b0c413b6875c9b154fc053b86641538e46ac56d63279950c70a1910217f7d6ef92d20b8e914e6b68bb7f19a58c6a4a653879ee2ea982bded0

test:
  secret_key_base: bafb8d3eefdee813e33d357415a029a7c9b622492dc60a7ff2d9071ad8974dfd045e99c115885d517a7a191777f84348681931ff293ebc3ca3f7006b01586236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
